async function run() {
  console.log('Data backup stub');
}

run().catch(err => {
  console.error(err);
  process.exit(1);
});


